### ISSUE TITLE
what is 'text section'?

### ISSUE THREAD

**Issue by cmcnamara87** [Bio-LarK/orpha#104]
I assumed it was the abstract, there are no text sections in drupal.

**Comment by tudorgroza** [comment]
The new data structure splits the textual description into several text sections - each of which may have a type, the content and, because they appear in a certain order, I've introduced the order attribute.

The content types are there - but I didn't manage to implement the import, as it comes from a different set of files.

The idea would be to show a 'stream' of textual sections, each of which can be edited separately.

**Comment by cmcnamara87** [comment]
Okay all good.
